### PR TITLE
Fix url_refresh variable for world region

### PR DESCRIPTION
**Pull request by seanford**
Starting my attempt to get this working for my HA setup...I think I have a V2 sock (USA based).  Couldn't authenticate...caught this typo.  Seems I can connect now.

### CODE REVIEW

**Review by seanford — COMMENTED** [review]
Updated this to allow testing of world region.

**Comment by ryanbdclark** [comment]
Thanks for contributing

If you do have a V2 sock it would be great if you were able to share your JSON repsonses you get from the Owlet API. I only have a V3 sock so all my testing has been done purely with that.

If you haven't seen it I have written an integration for homeassistant also, this can be found [here](https://github.com/ryanbdclark/owlet) I have submitted a pull request to merge this into the core however this may take some time. In the meantime however you can install this via HACS. As mentioned above I've only got a V3 sock so currently the integration only supports the V3 sock and will explicitly ignore any other socks when you add the integration. I'm happy to add support for V2 socks however if you able to provide the API responses. Also happy if you want to work on this yourself and submit a pull request on the HA  integration

**Comment by seanford** [comment]
Absolutely...happy to contribute even a little.  I'm in the USA and got the sock last year, so what I have is the Dream Sock.  I believe the socks are identical and that is what they created a new app in the US...to take the same data and display it differently.  See here:  https://support.owletcare.com/hc/en-us/articles/4418669476237-Dream-Sock-and-Smart-Sock-3-Differences

Your HACS integration is how I found the typo, tracing it back to the pyowletapi module.  I think in order for me to test it, you need to bump the version and the dependency version so it pulls the new code.  I tried uninstalling and re-reinstalling this morning and got the same "Unknown error occured" as I was getting before.  I think you'll also need to upload the new version to PyPi, which is where it pulls the dependencies from.  

Also, while I have a programming background, Python is a bit new to me and I'm still getting used to all of Githib's features and quirks, so excuse the extra pull requests.  I'm a Real Estate Broker now and I'm on house arrest recovering from back surgery, so what better time to have some fun with this.  lol

Thanks for all of yo9ur work on this...I'm sure there are many who appreciate it like I do.

**Comment by ryanbdclark** [comment]
I had heard of a dream sock but didn't know what it was, that's interesting. Sounds like the same device but just a different app like you suggested. I'd suspect that this should just be picked up as a V3 in that case.

I've just updated pyowletapi on PyPi and also made the required changes in the integration. You should see this available to install in HACS now as version 2023.7.1. Let me know how you get on!

Don't worry I'm still getting used to GitHub's quirks too

**Comment by seanford** [comment]
Yep, that worked!   Looks to be working normally, but I'll have to wait until this evening or when my wife lets me test it with the baby to know for sure.  We have a 2 story house and it doesn't reach all the way downstairs at times.

Will let you know once I've tested her wearing it.   But it set up properly and is reporting signal strength and battery pct so looks like we're good to go.

Now I just have to find a way into the cameras.

**Comment by ryanbdclark** [comment]
That’s good to hear! I do have a camera too and was looking at how to integrate that. Since then however my son has moved into his own room with a camera that has a physical stand-alone monitor and have stopped using the owlet camera, would be good to have the camera integrated too though, if I get time at some point I’ll have another look, if you/someone else hasn’t already figured it out.

**Pull request merged**
